### ISSUE TITLE
Improve receipt.json handling for failed deployments

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1191]
We should not produce `receipt.json` if the deployment failed before actually creating any cloud resources. We should add a `success` field to note successful and unsuccessful cloud deployments.
[Slack discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1649924321846159)

Related to https://github.com/api3dao/airnode/issues/1188

**Comment by kolenic-martin** [comment]
Hi @amarthadan, in today's batch, I've tested this by attempting to run the deployment with my Internet connection shut down, which means the deployment could not even begin. This did not produce a `receipt.json`. 

Another scenario I did was breaking off a deployment in the middle of deploying and attempting to redeploy again, doing it on GCP. As there were already some resources that have not been removed, this produced a failure. The `success` field indicated `false`. 

Finally, I scrapped the project and created a new one to perform another deployment on GCP without any interruptions. This went smoothly and the `receipt.json` file had `true` in the `success` field. 

Since this works as intended, I'm moving it to Done.
