### ISSUE TITLE
Add hardcoded whitelisting into the config file

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1197]
API providers don’t want to make their endpoints public, and they don’t want to have to make transactions to whitelist requesters. This means there is no way for them to use Airnode at the moment (which is why they have been directed towards relaying metadata).

Instead, we want the user to be able to hardcode whitelistings for endpointId-requester pairs (similar to how the current authorizers work) in the config file. This should probably go inside the respective `chains` object, but we should talk about it.

[Slack discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1646929455160219)

```
{
  "chains": [
    "authorizations": {
      "requesterAuthorizations": {
        "$ENDPOINT_ID_1": [
          "$REQUESTER_1",
          "$REQUESTER_2",
          ...
        ],
        ...
      }
    },
    ...
  ],
  ...
}
```

Related to https://github.com/api3dao/airnode/issues/1196

**Comment by bbenligiray** [comment]
We're increasingly talking about authorizing requesters to have access to all endpoints of an Airnode. With that in mind, maybe `requesterAuthorizations` should be called `requesterEndpointAuthorizations` for future-proofness.

**Comment by vponline** [comment]
The other task #1196  specifies the field name as 'authorizers' and here we have `authorizations`, is the intention to rename the field or create a new field?

**Comment by bbenligiray** [comment]
An authorization is when you allow someone to use your Airnode. An authorizer is a contract that authorizes. So `authorizers` and `authorizations` refer to two distinct concepts, the specs are correct (other than [this](https://github.com/api3dao/airnode/issues/1197#issuecomment-1153665996)).

**Comment by vponline** [comment]
I see, thanks for explaining!

**Comment by vponline** [comment]
And just to confirm that should both `$ENDPOINT_ID_N` and `$REQUESTER_N`  be secrets in `secrets.env` and interpolated from there into `config.json`?

**Comment by bbenligiray** [comment]
Not necessarily, but I can see that happen. When that requester makes a request to that endpoint and the Airnode responds on a public chain, the fact that that requester is authorized for that endpoint will be visible anyway, so this is not really a secret. However, this authorization may have been defined for a private chain, and the Airnode operator may want to be able to publish their config without disclosing their exact authorizations there.
If you're asking this to decide how you should create test fixtures, you don't need to do interpolation.

**Comment by amarthadan** [comment]
Moving this to `Blocked` until the [Slack discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1656334347924069) is resolved.

**Comment by amarthadan** [comment]
No longer blocked, moving to `TODO`, @vponline move it back to `In progress` when you start working on it again.

**Comment by amarthadan** [comment]
Hmm, in order to test all the cases one would have to:
* create and deploy an authorizer contract that authorizes `requesterA`
* allow `requesterB` in the config
* make 3 requests with `requesterA`, `requesterB` and `requesterC`, where `requesterA` and `requesterB` get authorized and `requesterC` doesn't.

Is that correct? Writing a contract sounds like something for you @Siegrift. What do you think?

**Comment by Siegrift** [comment]
Yeah, I'll test this.

**Comment by Siegrift** [comment]
Works as expected. 

FYI (and I guess good learning opportunity):

- I’ve used the already deployed [authorizer contracts](https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/deployments/references.json#L64) on testnets. I used ropsten specifically. (@wkande It could be mentioned explicitly in https://docs.api3.org/airnode/v0.8/concepts/authorization.html that you don't need to deploy your own).
- I’ve tested this using modified airnode-examples (see below)
- First, I’ve deployed a requester `yarn deploy-requester` as I want to authorize this requester with the authorizer contract)
- Docs say to do so via admin CLI (I used the CLI from the monorepo package using `yarn cli …`).
- RequesterAuthorizerWithAirnode [supports self-authorization](https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/contracts/whitelist/WhitelistRolesWithAirnode.sol#L133) (@wkande this should be more clear in docs) so I need to make the transaction from the airnode-wallet (invoke the CLI command with the airnode mnemonic). 
- This means I need Airnode mnemonic so I run `yarn create-secrets` from the examples, then via admin CLI `yarn cli derive-airnode-address --airnode-mnemonic="eye expect kingdom rich jelly rotate jealous draft place afford essence jungle"` (mnemonic comes from generated secrets)
- I then send some funds to the derived airnode address using MM
- Ran `yarn cli set-indefinite-whitelist-status --mnemonic="eye expect kingdom rich jelly rotate jealous draft place afford essence jungle" --requester-address="0x843e1D125747CE69b26eA511326608CFe58653AE" --provider-url="https://ropsten.infura.io/v3/e613d1b1bc844fc79cbd20d563a8c9ce" --requester-authorizer-with-airnode-address="0xf18c105D0375E80980e4EED829a4A68A539E6178" --endpoint-id="0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4" --indefinite-whitelist-status=true --airnode-address="0x5FDEF9682C821D655FFE156c5422381dD87B9209"`
- Double checked via `yarn cli get-whitelist-status --provider-url="https://ropsten.infura.io/v3/e613d1b1bc844fc79cbd20d563a8c9ce" --requester-authorizer-with-airnode-address="0xf18c105D0375E80980e4EED829a4A68A539E6178" --endpointId="0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4" --requester-address="0x843e1D125747CE69b26eA511326608CFe58653AE" --airnode-address="0x5FDEF9682C821D655FFE156c5422381dD87B9209"`. The result was `Output: {"expirationTimestamp":0,"indefiniteWhitelistCount":1}` This output could be more user readable, wdyt ?.
- Deployed another requester using airnode-examples (address “0x230B174Af585f91C6081224373cB364403ea23E4”)
- I’ve modified the config JSON like this: 
```
authorizers: {
        requesterEndpointAuthorizers: ['0xf18c105D0375E80980e4EED829a4A68A539E6178'],
      },
      authorizations: {
        requesterEndpointAuthorizations: {
          '0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4': [
            '0x230B174Af585f91C6081224373cB364403ea23E4',
          ],
        },
      },
 ```
- Ran `yarn create-airnode-config`, `create-aws-secrets` and `yarn deploy-airnode api3/airnode-deployer-dev:bc4a8887002a08f44a6f9fd01b80bfb1ae35f425` to deploy the airnode
- Ran `yarn derive-and-fund-sponsor-wallet`, `yarn sponsor-requester`, `yarn make-request` (success), `yarn make-withdrawal-request` to make a request using the hardcoded requester
- Double checked with `yarn cli get-whitelist-status --provider-url="https://ropsten.infura.io/v3/e613d1b1bc844fc79cbd20d563a8c9ce" --requester-authorizer-with-airnode-address="0xf18c105D0375E80980e4EED829a4A68A539E6178" --endpointId="0xfb87102cdabadf905321521ba0b3cbf74ad09c5d400ac2eccdbef8d6143e78c4" --requester-address="0x230B174Af585f91C6081224373cB364403ea23E4" --airnode-address="0x5FDEF9682C821D655FFE156c5422381dD87B9209"` and the output `{"expirationTimestamp":0,"indefiniteWhitelistCount":0}` which means that the hardcoded authorization works
- Changed requester contract address to `0x843e1D125747CE69b26eA511326608CFe58653AE` in `packages/airnode-examples/deployments/ropsten.json` 
- Ran `yarn derive-and-fund-sponsor-wallet`, `yarn sponsor-requester`, `yarn make-request` (success), `yarn make-withdrawal-request` (this is using the authorizer contract)
- Finally, `yarn deploy-requester`, `yarn derive-and-fund-sponsor-wallet`, `yarn sponsor-requester`, `yarn make-request` (failed, because the contract is unauthorized), `yarn make-withdrawal-request` 

<img width="2181" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/22679154/177725510-8a439cf3-5f85-44b4-bfd9-d84a65d29c94.png">
