### ISSUE TITLE
Move OIS to a separate repository

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1209]
Based on the [discussion in JIRA](https://api3dao.atlassian.net/browse/AN-733)

**Comment by kolenic-martin** [comment]
I've run a routine test with the coingecko example to check whether it still works (as I understood that Airnode needs to pull OIS as a dependency anyway) and it does, but it might not be enough to test if the split was performed correctly. @Siegrift could you perhaps advise?

**Comment by Siegrift** [comment]
Actually, this issue didn't affect Airnode at all, since what only happened now is that the code was moved to https://github.com/api3dao/ois. But the test you described will be necessary for https://github.com/api3dao/airnode/issues/1274 where we will start using the ois package.

I'll check whether it was published right, so we can consider this tested.
