### ISSUE TITLE
Move from API keys to route-based authentication for HTTP gateways

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1374]
Based on the [Slack discussion](https://api3workspace.slack.com/archives/C02AYRX8D89/p1659538932266949).

We want to get rid of the API keys for HTTP gateways and instead use a randomly generated route for the gateways' endpoints.
What needs to be done (roughly):
* Remove `apiKey` field from the config
* Remove API key initialization from Terraform recipes
* Turn off API key authentication in the OpenAPI templates
* Generate the random path section of the endpoint and update OpenAPI templates to use it
* Update the local HTTP gateways implementation accordingly

**Comment by martinkolenic** [comment]
I managed to test the HTTP and Signed Data gateways by sending a request to the newly-generated addresses via Postman. Since this still needs some documentation, it took me a moment to figure out the fact that an API key is not included in the request headers either but I am sure this will be clear when the docs are done.

**Comment by vponline** [comment]
@martinkolenic  The docs PR is open here: https://github.com/api3dao/api3-docs/pull/1025 so please feel free to also have a look at that if you have a chance. Your input is always appreciated in case you see something that is not clear :smile:

**Comment by martinkolenic** [comment]
Hi @vponline, thanks for pointing me in the right direction - I thought the changed docs had already gone live. I've just read your changes and these seem to be exactly what I was missing so we're good to go.
