### ISSUE TITLE
Figure out why can't the Airnode be deployed to the `ap-northeast-3` AWS region

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1503]
Regarding https://github.com/api3dao/airnode/issues/1429#issuecomment-1269827278

**Comment by dcroote** [comment]
I've confirmed Airnode can be deployed to `ap-northeast-3` with a blockchain request, HTTP gateway request, and HTTP signed data gateway request. CloudWatch logs were showing up under the `ap-northeast-3` region as expected. It's possible the previous error in the referenced comment was transient or AWS has increased the number of services in the region since the test.

**Comment by bbenligiray** [comment]
One could only wish for periodic CI across all supported regions
