### ISSUE TITLE
Unhandled error in logging when the API call fails

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1547]
From #dev-support:

![Screenshot from 2022-11-23 11-30-11](https://user-images.githubusercontent.com/19530665/203501307-67baa4df-2ad2-4400-9c7e-6113eaa4e278.png)

**Comment by Ashar2shahid** [comment]
To add to this issue, A fail transaction isn't generated either.

**Comment by andreogle** [comment]
The stack trace suggests that the issue is with this line: https://github.com/api3dao/airnode/blob/6ade99798d832543cb64a03ef737be4c2accd94f/packages/airnode-utilities/src/logging/logging.ts#L120

I ran `yarn build` and looked at line 113 in `airnode-utilities/dist/logging/logging.js`

**Comment by dcroote** [comment]
Thanks to the generous provision of a `config.json` that reproduces the error by @peptide-origami, I've identified the issue occurs specifically if **both** of the following are true:
1. In the config, the log format is `json` i.e. `"logFormat": "json"` (rather than `"logFormat": "plain"`, which is what our configs tend to use).
2. A gas price strategy fails

While this does occur for `v0.9.1`, an unexpectedly pleasant surprise is that the error no longer occurs with the latest master thanks to #1549, which changed `ERROR` to `WARN`. I confirmed this by also testing the prior master commit, `f3de2677528f8e58684d44dcbc1a2782af62660a`, which failed. Since #1549 isn't a genuine solution to `stack` being `undefined`, I'll work to address that next.

**Comment by dcroote** [comment]
@martinkolenic to test this one you can use the following setup:
 - coingecko integration in `airnode-examples`
 - Use local blockchain and the `airnode-client` (versions below)
 - Change `logFormat` from `plain` to `json` in `config.json`


This setup should fail with an error like in the screenshot above with `v0.9.1`, succeed with the latest `master`, and (though you cannot test this part just yet) succeed with the upcoming `v0.9.2` release.

**Comment by dcroote** [comment]
Great, thanks @martinkolenic! As part of your testing of the v0.9.2 snapshot packages (https://github.com/api3dao/airnode/issues/1588), can you confirm that the error no longer occurs?

**Comment by martinkolenic** [comment]
Hi @dcroote, yes, I did test this issue as one of the scenarios when testing the pre-release packages, and this is fixed there as well.

**Comment by dcroote** [comment]
Great, thanks @martinkolenic
