### ISSUE TITLE
Airnode PRs are failing on the E2E test step

### ISSUE THREAD

**Issue by aTeoke** [api3dao/airnode#1551]
A number of airnode PRs are failing on the E2E test step with the same error: Unable to find value at path: 'market_data.current_price.usd'.

related discussion: https://api3workspace.slack.com/archives/C02AYRX8D89/p1669272881427619

**Comment by dcroote** [comment]
Debugging (in-progress):
- [x] Is this specific to the E2E integration? **No**: the basic `coingecko` integration also fails with the same error for failing `airnode-client-dev` images
- [x] Is the API responding. **Yes**.
- [ ] What is the actual API response? This appears to be different (potentially in encoding or how `_path` is evaluated) based on the commit despite having an identical `config.json`...

**Comment by Siegrift** [comment]
The reason is  https://github.com/axios/axios/issues/5298 the response in the Airnode when run from a docker container looks like this:

<img width="1796" alt="image" src="https://user-images.githubusercontent.com/22679154/203967447-eb26ac7a-b932-4070-a186-2ad550f7e70d.png">

Unfortunately, I had to add a log to print out the request response (we don't log this because there can be sensitive information). Not sure if we should not revisit this decision, because the logs are not helpful.

**Comment by martinkolenic** [comment]
Hi @Siegrift , I assume this will be tested at the first completed PR, correct? Don't think we can test this from an user's perspective. I'll move this to Done if you give me an A-OK.

**Comment by Siegrift** [comment]
>  I assume this will be tested at the first completed PR, correct?

Since https://github.com/api3dao/airnode/pull/1553 passed the tests we can consider this tested. Feel free to move to DONE.
