### ISSUE TITLE
Replace airnode withdrawal logic with isolated function

### ISSUE THREAD

**Issue by aTeoke** [api3dao/airnode#1558]
Based on [this thread](https://api3workspace.slack.com/archives/C02AYRX8D89/p1646141484989579).

The current withdrawal logic isn’t compatible with Airkeeper, PSP, etc. and sponsor wallets are likely to be used over long time horizons by users.

Withdrawals still should be supported however as otherwise users will inevitably not read the relevant documentation and generate support issues or complaints when they cannot withdraw funds. 

An isolated function for handling withdrawals fulfils these objectives.

**Comment by bbenligiray** [comment]
The workflow I'm imagining for this is that the sponsor [signs](https://eips.ethereum.org/EIPS/eip-1271) a withdrawal request and sends it to the API of this "withdrawal node", and the withdrawal node responds with a signed transaction that executes the withdrawal. Then, the sponsor sends this signed transaction to a blockchain provider to have it confirmed. Advantages compared to on-chain request–response:
- The [withdrawal remainder](https://docs.api3.org/reference/airnode/latest/deployment-files/config-json.html#options-withdrawalremainder) is now a withdrawer-side thing rather than an Airnode config-side thing
- It's not clear to most users what a sponsor contract should do to be able to withdraw. If a multisig was set as the sponsor, withdrawals wouldn't be supported out of the box. Requiring an ERC1271 signature for withdrawals would alleviate these issues.
- The Airnode does not need to have access to a blockchain provider (in the case that an EOA signature is provided, ERC1271 signatures would require blockchain provider access). This is a nice way of winding down services on a chain ("we're no longer serving chain X but you will be able to request withdrawals on it for a year")

**Comment by bbenligiray** [comment]
Closed to be tracked by https://github.com/api3dao/airnode-protocol-v1/issues/163
