### ISSUE TITLE
Create E2E test for RRP fulfilments estimating gas

### ISSUE THREAD

**Issue by aTeoke** [api3dao/airnode#1692]
It has been decided on weekly planning call that E2E test for #1589 is not mandatory for the release of 0.11 since we want to release asap with the functionality included. 

Please create E2E test

**Comment by dcroote** [comment]
Gas estimation, rather than specifying a `fulfillmentGasLimit` will be the default going forward. Therefore, I am closing this separate issue as updating one or more of the existing E2E tests (which will be relatively straightforward) should be included when addressing https://github.com/api3dao/airnode/issues/1589

**Comment by dcroote** [comment]
Reopening. It was not straightforward to adjust an existing E2E test because the revised implementation involves a new contract `AirnodeRrpV0DryRun`. See my comment on the PR [here](https://github.com/api3dao/airnode/pull/1817#pullrequestreview-1517765112).
