### ISSUE TITLE
test:coverage in airnode-protocol does not work

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1736]
When I run `yarn test:coverage` in airnode-protocol, I get
```
Error in plugin solidity-coverage: TypeError: Cannot read properties of undefined (reading 'events')
```

**Comment by dcroote** [comment]
This is due to package version incompatibilities. When running `yarn bootstrap`:
```sh
warning "workspace-aggregator-0f9ab394-376f-407f-b555-7e71990b2b0e > @api3/airnode-protocol > solidity-coverage@0.8.2" has incorrect peer dependency "hardhat@^2.11.0".
```

As the warning suggests, `solidity-coverage` version `0.8.0` and above [requires hardhat 2.11.0](https://github.com/sc-forks/solidity-coverage/releases/tag/v0.8.0), whereas we are using hardhat `2.10.2`. Upgrading `hardhat` is probably preferable, though others have [had success](https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/2659?sort=top#discussioncomment-5056404) downgrading `solidity-coverage` e.g. to `0.7.22`

**Comment by dcroote** [comment]
@bbenligiray would you like to test by confirming the command now works after an install of the latest master?

**Comment by bbenligiray** [comment]
Confirmed that the fix works and moved the card on the board, thanks
