### ISSUE TITLE
Airnode attemps to fail the request when the sponsor wallet is invalid

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#1749]
Run `yarn && yarn main` on https://github.com/bbenligiray/fulfillment-analysis and you will see a bunch of reverted transactions that attempt to call `fail()` with the `errorMessage` `Sponsor wallet is invalid...`. These `fail()` calls of course revert because the sponsor wallet is invalid. This is a DoS vector for certain advanced user patterns for RRP (where you let the end-user specify the sponsor wallet).

When the sponsor wallet for a request is invalid, Airnode should just log it and ignore it on-chain.

**Comment by dcroote** [comment]
I was able to reproduce this by using the wrong sponsor wallet address:
https://sepolia.etherscan.io/tx/0x54478cdca3f585fcb07ed85180ed87eee8401dc2b3008be64f3bf570a499ef2d

The relevant code for the error is below, with `RequestErrorMessage.SponsorWalletInvalid` being the error message `Sponsor wallet is invalid`:
https://github.com/api3dao/airnode/blob/a14f3b0325abc3a6d981ddbfa2a39d8f4f6a85a2/packages/airnode-node/src/api/index.ts#L104-L118


<br>
<br>

> When the sponsor wallet for a request is invalid, Airnode should just log it and ignore it on-chain.

It turns out we already do this for withdrawal requests:
https://github.com/api3dao/airnode/blob/a14f3b0325abc3a6d981ddbfa2a39d8f4f6a85a2/packages/airnode-node/src/evm/verification/request-verification.ts#L8-L28

**Comment by aTeoke** [comment]
Just to add, we are only patching the current version 0.11.0 upon agreement on Airnode weekly call.

**Comment by dcroote** [comment]
@aTeoke - to test this you can follow the airnode-example `coingecko` flow, but before making the request, change the sponsor wallet to something random (invalid) in the `coingecko/request-utils.ts` file:

https://github.com/api3dao/airnode/blob/f49228a15f73aa8d21001bd305ae2d3f5180db59/packages/airnode-examples/integrations/coingecko/request-utils.ts#L17-L21

Before this PR, the result would be a failed tx like I linked to in my comment above. Now, Airnode ignores the request because the sponsor wallet is invalid and does not make the API call or submit a tx.
