### ISSUE TITLE
Cloud Development Kit integration - "cdk3"?

### ISSUE THREAD

**Issue by sam-goodwin** [api3dao/airnode#178]
The AWS Cloud Development (https://github.com/aws/aws-cdk) provides a high level, imperative abstraction of AWS CloudFormation. It has rapidly accelerated the rate at which AWS applications can be built and is growing rapidly.

I think there's an opportunity to build an API3 adapter Construct for the CDK which automates airnode and API3 configuration. The goal is to provide an almost-instant adapter for the CDK's [API Gateway](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigateway-readme.html) and [GraphQL](https://www.npmjs.com/package/@aws-cdk/aws-appsync) abstractions so that existing CDK teams could drop API3 into their projects. 

## Experience

1. Developer uses the CDK to build an ordinary Web2 API in AWS.
```ts
import * as apigw from '@aws-cdk/aws-apigateway';
import * as api3 from '@airnode/...';

// construct a OpenAPI compatible API
const myWeb2Api = new apigw.RestApi(..)
```

2. Drop in the `api3` construct library to deploy an Airnode.

```ts
// provision an Airnode
const airnode = new api3.Airnode(scope, 'Airnode');
```

3. With our Airnode hosted, we can now add Web2 APIs to it - lifting them into Web3.

```ts
// adapt that OpenAPI to API3.
const myWeb3Api = airnode.addApi(myWeb2Api);
```

This construct will introspect into our RestAPI to automatically synthesize OIS (leveraging: https://github.com/api3dao/airnode/issues/152)

4. Deploy - simple one line command to deploy the entire system.

```
cdk deploy
```

## Wider Integration

We should also support other imperative IaC abstractions such as [Pulumi](https://www.pulumi.com/) and [TerraformCDK](https://github.com/hashicorp/terraform-cdk). These tools are becoming increasingly popular due to their utility - managing complex infrastructure as re-usable code packages instead of as YAML configuration allows for interesting use-cases such as the one described here. Such an integration is a low investment that exposes API3 to a huge number of modern projects under active development.

## Support for other Web3 Resources?

I'm new to API3 and don't yet have the full picture, but I'm curious if there are other aspects that can be modeled as Resources and managed with CloudFormation. I noticed that `@airnode-starter` has a bunch of scripts for creating assets on ETH: https://github.com/api3dao/airnode-starter/tree/main/scripts. I wonder if these could instead be managed as Resources and configured with CDK Constructs?

```
new MasterWallet()
```

**Comment by sam-goodwin** [comment]
It looks like `@airnode/deployer` is not published to NPM. I need to depend on it to wrap the resources in a Construct. Is there a plan to release that?

**Comment by bbenligiray** [comment]
Hi @sam-goodwin, thanks for bringing this up, definitely sounds promising and in line with the vision. First let me go over our current deployment goals, and then how this might fit in.

## Existing deployment strategy

API3 primarily cares about two things (and I have to point out the difference between Airnode, the software, and API3, a specific user of that software):
1. Deployment should be as easy as possible for frictionless API provider onboarding
2. We don't want to be vendor-locked to a specific cloud provider (and even want to mirror deployments across cloud providers, a mix of #154 and #155)

For (1), we packed everything needed to deploy the node in a Docker container that the user can run with a [single command](https://github.com/api3dao/airnode/blob/master/Docker.md#deploy-first-time). For (2), we went with Terraform and Serverless Framework inside the deployer container because both are fairly vendor-agnostic (and we probably will drop Serverless at some point in favor of pure Terraform).

## CDK

Allowing users to extend their infrastructure with an Airnode is a distinctly different goal (but it's very valid for adoption). As such, it's not constrained by the same requirements, i.e. depending on AWS-specific tools is not a deal-breaker.

The deployer package in the monorepo is used to implement the container functionality that uses Terraform and Serverless under the hood. I think what you're suggesting is an alternative to that, so this CDK integration would be an alternative to the deployer package (and thus wouldn't need to import it). It would need to import the node package (as the deployer package does), but we didn't publish that either. There are two options here: (1) publish the node package and import that at a separate CDK integration repo, (2) implement the CDK integration as a monorepo package (or even embed it in the deployer package).

## Web3 interaction

Maybe? This needs some thinking, especially regarding how the wallet that will be making these transactions will be handled.

**Comment by bbenligiray** [comment]
This is not a priority for core development due to being vendor-specific. Feel free to comment if you want to contribute to it.
