### ISSUE TITLE
Request a new deployment, Darwinia Network

### ISSUE THREAD

**Issue by jiguantong** [api3dao/airnode#1793]
Come from https://docs.api3.org/reference/airnode/latest/
### Mainnet: Darwinia
Rpc: rpc.darwinia.network
Exploer: https://darwinia.subscan.io/
EVM: https://chainlist.org/chain/46

### Testnet: Pangolin
Rpc: pangolin-rpc.darwinia.network
Exploer: https://pangolin.subscan.io/
EVM: https://chainlist.org/chain/43

**Comment by aTeoke** [comment]
I assume you will deploy it yourself in #1792 right? Can I close this ticket then?

**Comment by jiguantong** [comment]
> I assume you will deploy it yourself in #1792 right? Can I close this ticket then?

In #1792 I deployed it myself just for local testing. We still need a new deployment on Darwinia and Pangolin, can you help with that? Or what do I need to do?

**Comment by bbenligiray** [comment]
> In https://github.com/api3dao/airnode/issues/1792 I deployed it myself just for local testing. Is this enough for a production environment? Is there anything else I need to do?

If your AirnodeRrpV0 address is `0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd` you're all good regarding contract deployment. Note that this is not a guarantee of correct behavior if the chain isn't a regular EVM. For example, it would require a significant effort to have Airnode be compatible with some chains https://github.com/api3dao/airnode/issues/1082 In short, if your chain doesn't behave like all the other chains in some aspects, test your use case extensively. If it's perfectly EVM compatible, you're good to go.

> I assume you will deploy it yourself in https://github.com/api3dao/airnode/issues/1792 right? Can I close this ticket then?

On one hand, the protocol is not deployed on this chain (at least it doesn't appear to so looking at the repo), so the issue can remain open. However, we don't deploy on chains on demand because making sure of the above is an unscalable amount of work. We need a well-defined flow for creating and testing new chain deployments, after which we can accept contributions. Until then, we won't address these kinds of issues.
