### ISSUE TITLE
Ignore casing when comparing address in OEV gateway

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#1963]
[Here](https://github.com/api3dao/airnode/blob/e07a3b9952e48139f70b1fb7344a6f30b97afdbc/packages/airnode-node/src/workers/local-gateways/validation.ts#L279) we should make sure to allow comparing EIP-55 address with lowercase one.

**Comment by dcroote** [comment]
Here as well?
https://github.com/api3dao/airnode/blob/1c49d6fe602eb430093a73f8339ec0034afdbcae/packages/airnode-node/src/handlers/sign-oev-data.ts#L15

Though I'm actually having a hard time understanding how both addresses can be anything but Checksum addresses in the code you linked to:

https://github.com/api3dao/airnode/blob/1c49d6fe602eb430093a73f8339ec0034afdbcae/packages/airnode-node/src/workers/local-gateways/validation.ts#L277-L279

Here, `airnodeAddress` is the Checksum address since that is what ethers within `getAirnodeWalletFromPrivateKey()` returns. As for `beacon.airnodeAddress`, it seems this too has to be the Checksum address, since otherwise ethers `verifyMessage` would fail because the signature, generated with ethers `signMessage` (right?), returns the Checksum address.

https://github.com/api3dao/airnode/blob/1c49d6fe602eb430093a73f8339ec0034afdbcae/packages/airnode-node/src/workers/local-gateways/validation.ts#L177-L182

**Comment by Siegrift** [comment]
I actually wasn't sure just by looking at the code, so I assumed this is possible. If you've verified this is not an issue we can close this one.

**Comment by Siegrift** [comment]
I believe this works as expected.
