### ISSUE TITLE
Fix building Docker images locally

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airnode#2014]
See the steps to reproducible the issue [here](https://discord.com/channels/758003776174030948/1062910618031636571/1272831406216843326). There is the following error:

```
error Couldn't find any versions for "@api3/airnode-admin" that matches "snapshot-local"
```

This has been briefly discussed internally [here](https://api3workspace.slack.com/archives/C02AYRX8D89/p1723537851397659), but so far without resolution.

**Comment by dcroote** [comment]
Ah, it turns out this very non-intuitive error is a result of not having a `changeset` affect a package, which in turns results in packages not being published to the local npm registry, and therefore airnode-admin can't be found. I've run into this myself before: https://github.com/api3dao/airnode/issues/1585#issuecomment-1420226393 and it happens after every fresh release (since all changesets are cleared) e.g. [for v0.14.2 here](https://github.com/api3dao/airnode/actions/runs/9753460312/job/26918839398):

```
#5 [2/3] RUN npm set registry http://172.17.0.3:4873/ &&     yarn global add @api3/airnode-admin@snapshot-3b81fd6b4300b7a13e288e8dda133ad1fe3e0d17 &&     ln -s /usr/local/share/.config/yarn/global/node_modules/@api3/airnode-admin/dist /app &&     adduser -h /app -s /bin/false -S -D -H airnode-admin
#5 0.771 yarn global v1.22.19
#5 0.827 [1/4] Resolving packages...
#5 0.885 error Couldn't find any versions for "@api3/airnode-admin" that matches "snapshot-3b81fd6b4[30](https://github.com/api3dao/airnode/actions/runs/9753460312/job/26918839398#step:7:31)0b7a13e288e8dda133ad1fe3e0d17"
```

The solution is to run `yarn changeset` and commit the resulting file along with the source code changes and then proceed with `yarn docker:build:local`.
