### ISSUE TITLE
Implement HEALTHCHECK for the airnode-client container

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#224]
Implement [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) for the [`airnode-client` image](https://github.com/api3dao/airnode/blob/pre-alpha/Dockerfile-client), update the [docs](https://github.com/api3dao/airnode/blob/pre-alpha/Docker-client.md) to restart the container as discussed [here](https://stackoverflow.com/a/61956475/14558682) (or feel free to come up with a better way).

**Comment by Ashar2shahid** [comment]
There are two scenario in which the airnode-client container can stop working:
1. The invoke command halts i.e it takes longer than a minute to fulfill requests.
2. There is some error in the code/directory that causes the invoke command to fail instantly.

In the case of 1. Docker has the ability to tag containers from healthy to unhealthy and we can use something like [this ](https://github.com/willfarrell/docker-autoheal) to restart the containers ( I addressed this in the PR).

However in case of 2. Docker does not tag the container has unhealthy and assumes its healthy since it does not throw a non error code. 

One way to solve this would be to throw an error code on any [unhandled promise exceptions](https://blog.sixeyed.com/docker-healthchecks-why-not-to-use-curl-or-iwr/) but that would require changing the code and adding a bunch of try catch (or something else) to throw an error code. 

Another way would be, is that we write a `healthcheck` script that pipes in the `yarn invoke` output and then outputs an errorcode if it detects error in the airnode code this would cause the kill command to run and then docker's restart policy would restart the container.

As it stands I've addressed 1. in the PR above but not 2.

**Comment by MrAngus666** [comment]
@Ashar2shahid 
Related to two:
Have you thought on try to catch on the top level of the application and throw an error there?
Also,
Related to docker-autoheal, are we already considering for long term to run docker in production just with docker or do we prefer to use kubernetes (that have their own thing to recycle unhealthy instances)? @bbenligiray thoughts on this?

**Comment by Ashar2shahid** [comment]
@MrAngus666 
I thought of that but didn't try that. Something like this in the invoke script would probably work. 
```
process.on('uncaughtException', function(err) {
  console.log('Caught exception: ' + err);
  process.exit(1);
}); 
```
I wasn't comfortable with handling it on the top level but this should work.
not really sure how else, one would globally catch exceptions in node, open to suggestions.

Kubernetes seems like overkill for this task, Docker ships with swarm which has the ability to recycle unhealthy containers, although I felt adding a layer on top would be a bit much since autoheal does the same thing.

**Comment by bbenligiray** [comment]
Sorry I forgot to reply to these
>  are we already considering for long term to run docker in production just with docker or do we prefer to use kubernetes (that have their own thing to recycle unhealthy instances)?

Currently the main function of this image is to provide an easy to use integration environment and Docker is enough for that.

I was thinking that the goal of healthcheck would be to detect issues originating from the container rather than the node. If a node invocation errors, it doesn't mean that the container is unhealthy and a container restart won't do something that the next invocation won't do anyway (I mean the node already keeps restarting itself). So healthcheck is meant to check problems with the container beyond the node (for example an issue related to the linux image).

**Comment by MrAngus666** [comment]
This was merged in pre-alpha branch, closing this issue.
