### ISSUE TITLE
CI tests run twice when a commit is pushed to a PR

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#295]
At the moment the CI tests run twice when you push a commit to a PR from a non-forked repo (see Continuous Build #320 and #321
https://github.com/api3dao/airnode/actions/runs/771308103
https://github.com/api3dao/airnode/actions/runs/771308169

For more information
https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662

We're leaving this as is for the moment because running the tests twice sometimes is not a big deal.

**Comment by Siegrift** [comment]
Adding comment for future somebody who looks at this issue.

It can't be done as of now. See: https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662
What we can do is change workflow so that it ONLY triggers to pushes to `main` and PRs to `main`
But we don't want to do that as of now.
