### ISSUE TITLE
Update config.json to include security scheme values

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#492]
Now that we can interpolate environment variables, we decided that `config.json` should house the security scheme values, to be outsourced to `secrets.env` if the user wants. @amarthadan suggested that these should go under OIS, but I disagree because it is not relevant to specifying an API or its integration at all. The alternative is putting it in `config.json`, which would look similar to https://docs.api3.org/next/reference/deployment-files/config-json.html#environment

**Comment by amarthadan** [comment]
This was already implemented in https://github.com/api3dao/airnode/pull/439. The credentials (an API key for example) is read from `ois.credentials` section. I'd say it has to be at the OIS level because we can have multiple OISes in the `config.json` (it's an array).

How it works now is that you can have multiple scheme definitions in `ois.components.securitySchemes` (following the OAS) and selecting one with `ois.credentials` section. The reason I designed it this way is that in the future I would like to follow the OAS example and allow one global credentials (what's currently in `ois.credentials` section) and allow local (per path) overrides. OAS is allowing the same thing when you want to set up for example one auth method for the whole API except for one path.

I'm open to suggestions, but this felt familiar enough to OAS so I followed thair example.

**Comment by bbenligiray** [comment]
My concern is that OIS is very similar to OAS in purpose (specifies an interface), so it's not appropriate for it to include security scheme values for the same reason. Also consider the case where the security scheme values for multiple OISes are defined as `${API_KEY}`. What the environment variable name will be (or what the API key value will be) is a `config.json`-level decision, and not an OIS-level one. We already support multiple OISes by having an `oisTitle` field (assuming unique OIS titles, which is probably not checked for).

We explicitly don't support path-specific security schemes, mostly because it has never been needed and will create confusion.

**Comment by amarthadan** [comment]
I don't think the similarity with OAS is a problem here. Also, the similar part is basically just the `apiSpecifications` section. We're already adding `endpoints` section anyway so I don't see a problem in adding `credentials` section as well.

As for multiple OISes and their API key variables they would have to be named separately, something like `${API_KEY_OIS_X}` and `${API_KEY_OIS_Y}`. But that would have to be done anyway, unless you want to use the same API key for multiple OISes (which you still can).

I don't really like the same setup as the `environment` field was. The point of the variable interpolation was (partly) that we can get rid of this arbitrary matching and we can just add fields where we need them. So, credentials for specific OIS should IMO go under the `ois`.

We can discuss it on the Airnode call.

**Comment by bbenligiray** [comment]
Closing this issue to be tracked by https://api3dao.atlassian.net/jira/software/projects/AN/boards/18/backlog?selectedIssue=AN-72
