### ISSUE TITLE
Integrations to webhooks are not supported

### ISSUE THREAD

**Issue by 37Rb** [api3dao/airnode#721]
## Description

A smaller but important part of the API economy is webhooks. When API providers want to allow users to be notified of events, they offer a webhook that calls back an endpoint provided by the user. We've already come across a user that wants their contract to be called from [Open Bank Project webhooks](https://apiexplorer.openbankproject.com/?tags=Webhook) in the Bitcoin Bankathon.

## Present Behavior

Only outbound requests via RRP or API polling via PSP.

## Desired Behavior

An Airnode user can register a contract function to be called when an API event occurs. Maybe use Airnode RRP to register the "Airhook". When the webhook is called, then the contract function is called via RPC. There may need to be a server run by the API provider to listen for webhook invocations.

**Comment by bbenligiray** [comment]
There are roughly two API patterns out there: One where the client pulls the data, and one where the client tells the API when to push the data (and webhooks belong to the second camp). The API connectivity problem approach goes "Push and pull API patterns have emerged, which implies oracle equivalents are necessary". In the Airnode protocol, users can pull data using RRP, or ask to have data pushed using PSP. Note that the problem we're trying to solve is not "I have an API that can push, how do I integrate it using Airnode" but rather "The user needs an oracle service that can push, how can we build that out of an existing API".

Although it feels natural to build an oracle service that pushes out of a webhook-based API, but there are practical reasons why you may not want to do that:
- Webhook APIs are extremely rare compared to the more traditional REST APIs (due to the reasons below). Therefore, if we required webhooks APIs to build push oracle services, we wouldn't have too many (and Beacons prefer push updates for example).
- Webhook APIs are far less standardized, which means it is difficult to standardize their integrations and protocolize their usage on-chain.
- Webhooks APIs are stateful, which means being much more error-prone. This is generally fine, because webhooks tend to be used to notify the client of events (to redraw a UI element for example), rather than delivering critical information. In our case, this worsened performance is very undesirable. I should note that Airnode also doesn't use the subscription features of JSON-RPC APIs that it uses to communicate with blockchains (and sticks to polling instead) and Airnode owes parts of its robustness to that.
- Finally, in practice, monetized webhooks APIs have very weird/unstandardized rules around their usage, such as "you can only subscribe up to 10 events simultaneously" or "you can only subscribe to an event for up to a day". In practice, this will result in unexpected oracle service outages just because the provider was enforcing an obscure rule that even they forgot about/don't realize its consequences.

So how PSP is implemented is that it allows push oracle services to be built out of regular REST APIs, which are ubiquitous, standardized and robust. A potential webhook integration will perform worse than this and will likely not be generalizable enough to be applicable to arbitrary APIs, so we aren't planning on working on it. I think it's a good idea to leave this issue open though, in case someone doesn't agree and wants to have a crack at it.

**Comment by bbenligiray** [comment]
About the hackathon participants specifically, I'm pretty sure that whatever data the webhook endpoints were providing was also available through the regular endpoints. So what they have two options
- Use PSP, which is not available yet
- Use an Airkeeper-like implementation to simulate a push oracle service on top of RRP

**Comment by 37Rb** [comment]
Thanks @bbenligiray! FWIW I didn't write this issue as a complaint. I wrote it in the negative "X doesn't do Y" format just to conform with how the other issues are written. I didn't expect regular webhooks such as these be supported by PSP.

It's also worth pointing out that this kind of traditional webhook support DOES NOT NEED to be part of the Airnode protocol. It can always be implemented application specifically which may make more sense as webhooks are less standardized. Also, as it's a different pattern, it also may make more sense to implement this in a separate software module than Airnode like we did with Airkeeper, if someone does decide to attempt it in the future.

**Comment by bbenligiray** [comment]
It's perfectly fine and useful to have "Airnode doesn't do X" type of issues

**Comment by bbenligiray** [comment]
Unlike https://github.com/api3dao/airnode/issues/263 I've never seen user demand for this but still keeping the issue open

**Comment by bbenligiray** [comment]
Closing because webhooks are inherently incompatible with RRP
