### ISSUE TITLE
Requests are no longer able errorable

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airnode#74]
There used to be a method to error a call
https://github.com/api3dao/airnode/blob/fd1fdf209ea22aba8b2bf980d4980011e850c955/packages/protocol/contracts/interfaces/IAirnode.sol#L119-L129
Now, the `errorCode` is returned in `statusCode` of `fulfill`:
https://github.com/api3dao/airnode/blob/696ebad7207b02ffba9b85f2bb57430425c7cd32/packages/protocol/contracts/interfaces/IAirnode.sol#L93-L105

All code about erroring needs to be removed. The node should try to call `fulfill()` and if that reverts, it should call `fail()` directly.

**Comment by andreogle** [comment]
Just to confirm, is `statusCode` supposed to be `0` or `null` if no error happened?

**Comment by bbenligiray** [comment]
`0`

**Comment by andreogle** [comment]
If the request errored and has no response data to return, what should be used for the `data` argument here? The value shouldn't matter since the client should check `statusCode` first, but I still need to call the `fulfill` function with something. 

Should I just use `0x0`? I'm sure if this is a valid value yet though

**Comment by bbenligiray** [comment]
Yes, `0x0` (or rather `ethers.constants.HashZero`) is fine
